# Generated by Django 2.2.7 on 2019-11-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
