# Generated by Django 2.2.7 on 2019-11-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
